In [4]:
import torch

In [5]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 4.6566e-10, 2.8099e-10],
        [8.5920e+09, 1.1210e-44, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [6]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0513, 0.7709, 0.1693],
        [0.7552, 0.4236, 0.7595],
        [0.4919, 0.4863, 0.4885],
        [0.6922, 0.8577, 0.4505],
        [0.3706, 0.7323, 0.9424]])


In [7]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [10]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [11]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.4437,  1.9971, -1.3362],
        [ 0.5128, -1.0558, -0.1331],
        [ 0.0361,  2.1837, -0.4887],
        [ 1.1272, -0.9629, -1.4825],
        [ 2.7131,  1.1538, -0.8052]])


In [12]:
print(x.size())

torch.Size([5, 3])


In [13]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.0976,  2.8077, -0.5769],
        [ 0.9788, -0.7342, -0.1267],
        [ 0.2032,  2.7750,  0.1234],
        [ 1.1602,  0.0325, -0.7814],
        [ 2.9146,  1.3385, -0.0333]])


In [14]:
print(torch.add(x, y))

tensor([[ 1.0976,  2.8077, -0.5769],
        [ 0.9788, -0.7342, -0.1267],
        [ 0.2032,  2.7750,  0.1234],
        [ 1.1602,  0.0325, -0.7814],
        [ 2.9146,  1.3385, -0.0333]])


In [15]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.0976,  2.8077, -0.5769],
        [ 0.9788, -0.7342, -0.1267],
        [ 0.2032,  2.7750,  0.1234],
        [ 1.1602,  0.0325, -0.7814],
        [ 2.9146,  1.3385, -0.0333]])


In [17]:
print(x)
print(x[:, 1])

tensor([[ 0.4437,  1.9971, -1.3362],
        [ 0.5128, -1.0558, -0.1331],
        [ 0.0361,  2.1837, -0.4887],
        [ 1.1272, -0.9629, -1.4825],
        [ 2.7131,  1.1538, -0.8052]])
tensor([ 1.9971, -1.0558,  2.1837, -0.9629,  1.1538])


In [18]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [19]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.2113])
0.21132001280784607


## NumPy Bridge
Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

In [20]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [21]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [22]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [23]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors
Tensors can be moved onto any device using the .to method.

In [24]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

## Tensor

In [25]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [26]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [27]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [28]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


## Gradients

In [29]:
out.backward()

In [30]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [31]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([-1158.8939,   -51.2829,  -535.9496], grad_fn=<MulBackward0>)
